version: "3"
services:
  postgres:
    image: postgres:10.5
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      # ユーザ＆パスワードは仮。リリースタイミングで変更する。
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    hostname: postgres
    restart: always
    user: root
  pgweb:
    # pgweb: overview
    # https://github.com/sosedoff/pgweb/wiki/Docker
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      # ユーザ＆パスワードは仮。リリースタイミングで変更する。
      - DATABASE_URL=postgres://root:root@postgres:5432/postgres?sslmode=disable
    links:
      - postgres:postgres
    restart: always
    depends_on:
      - postgres
